Bluesync in BLE Mesh: src/statistic/bluesync_statistic.h File Reference
bluesync_statistic.h File Reference
#include <stdint.h>
#include "../bluesync.h"
Functions
void statistic_bluesync_status (bluesync_timestamps_t *elem_master, bluesync_timestamps_t *elem_slave, size_t size)
Analyze and log synchronization statistics based on a series of timestamps.
void bluesync_statistic_init ()
Initialize the BlueSync statistics module.
void bluesync_statistic_deinit ()
Deinitialize the BlueSync statistics module.
Function Documentation
bluesync_statistic_deinit()
void bluesync_statistic_deinit ()
Deinitialize the BlueSync statistics module.
This function cleans up and close files
Definition at line 128 of file bluesync_statistic_bsim.c.
{
    fclose(node.file);
    synced_time_logger_deinit();
}
References node, and synced_time_logger_deinit().
Referenced by NATIVE_TASK().
bluesync_statistic_init()
void bluesync_statistic_init ()
Initialize the BlueSync statistics module.
This should be called once at system startup or before beginning a series of synchronization evaluations. It opens needed files.
Definition at line 114 of file bluesync_statistic_bsim.c.
{
    uint32_t device_number = bsim_args_get_global_device_nbr();
    node.file = open_stat("node_status", device_number);
    fprintf(node.file, "timeslot_idx" SEPARATION_TOKEN "rcv_time" SEPARATION_TOKEN
                   "local_time" SEPARATION_TOKEN  "estimation_master" SEPARATION_TOKEN "valid"
                   "\n");
    synced_time_logger_init();
}
References node, open_stat(), SEPARATION_TOKEN, and synced_time_logger_init().
Referenced by NATIVE_TASK().
statistic_bluesync_status()
void statistic_bluesync_status (bluesync_timestamps_t * elem_master, bluesync_timestamps_t * elem_slave, size_t size)
Analyze and log synchronization statistics based on a series of timestamps.
This function stores master and slave timestamp pairs into a CSV file.
Parameters
elem_master Pointer to the array of master timestamps.
elem_slave Pointer to the array of local timestamps captured by the slave.
size Number of timestamp pairs to process.
Definition at line 75 of file bluesync_statistic_bsim.c.
{
    uint8_t result_bitfield[NB_BYTES_BITFIELD] = {0};
    // Compute bitfield indicating timestamps available in both set
    bitwise_and_bitfields(result_bitfield, elem_master, elem_slave, NB_BYTES_BITFIELD);
    for (size_t i = 0; i < size; i++) {
        struct bluesync_msg_client_statistic stat = {
            .idx = i,
            .master_timer_ticks = elem_master->timer_ticks[i],
            .client_timer_ticks = elem_slave->timer_ticks[i],
            .estimation_master_ticks = elem_slave->remote_est_ticks[i],
            .valid = is_bit_set(result_bitfield, i),
        };
        bluesync_statistic_packet_status(&stat);
    }
}
References bitwise_and_bitfields(), bluesync_statistic_packet_status(), is_bit_set(), NB_BYTES_BITFIELD, and bluesync_timestamps_t::timer_ticks.
Referenced by end_sync_timeslot_process().