Bluesync in BLE Mesh: src/statistic/bluesync_statistic_bsim.c File Reference
bluesync_statistic_bsim.c File Reference
#include <zephyr/kernel.h>
#include "posix_native_task.h"
#include "bsim_args_runner.h"
#include <stdio.h>
#include <string.h>
#include "bluesync_statistic.h"
#include "../bluesync_bitfields.h"
#include <zephyr/logging/log.h>
#include "synced_time_logger.h"
Classes
struct node_stat
struct bluesync_msg_client_statistic
Macros
#define SEPARATION_TOKEN ";"
Functions
LOG_MODULE_REGISTER (bluesync_statistic_bsim, CONFIG_BLUESYNC_LOG_LEVEL)
void bluesync_statistic_packet_status (struct bluesync_msg_client_statistic *packet_status)
void statistic_bluesync_status (bluesync_timestamps_t *elem_master, bluesync_timestamps_t *elem_slave, size_t size)
Analyze and log synchronization statistics based on a series of timestamps.
static FILE * open_stat (char *filename, uint32_t device_number)
void bluesync_statistic_init ()
Initialize the BlueSync statistics module.
void bluesync_statistic_deinit ()
Deinitialize the BlueSync statistics module.
NATIVE_TASK (bluesync_statistic_init, BOOT, 101)
NATIVE_TASK (bluesync_statistic_deinit, ON_EXIT, 501)
Variables
static struct node_stat node
Macro Definition Documentation
SEPARATION_TOKEN
#define SEPARATION_TOKEN ";"
Definition at line 44 of file bluesync_statistic_bsim.c.
Referenced by bluesync_statistic_init(), bluesync_statistic_packet_status(), synced_time_logger_init(), and synced_time_logger_new_msg().
Function Documentation
bluesync_statistic_deinit()
void bluesync_statistic_deinit ()
Deinitialize the BlueSync statistics module.
This function cleans up and close files
Definition at line 128 of file bluesync_statistic_bsim.c.
{
    fclose(node.file);
    synced_time_logger_deinit();
}
References node, and synced_time_logger_deinit().
Referenced by NATIVE_TASK().
bluesync_statistic_init()
void bluesync_statistic_init ()
Initialize the BlueSync statistics module.
This should be called once at system startup or before beginning a series of synchronization evaluations. It opens needed files.
Definition at line 114 of file bluesync_statistic_bsim.c.
{
    uint32_t device_number = bsim_args_get_global_device_nbr();
    node.file = open_stat("node_status", device_number);
    fprintf(node.file, "timeslot_idx" SEPARATION_TOKEN "rcv_time" SEPARATION_TOKEN
                   "local_time" SEPARATION_TOKEN  "estimation_master" SEPARATION_TOKEN "valid"
                   "\n");
    synced_time_logger_init();
}
References node, open_stat(), SEPARATION_TOKEN, and synced_time_logger_init().
Referenced by NATIVE_TASK().
bluesync_statistic_packet_status()
void bluesync_statistic_packet_status (struct bluesync_msg_client_statistic * packet_status)
Definition at line 61 of file bluesync_statistic_bsim.c.
{
    k_mutex_lock(&node.mutex, K_FOREVER);
    {
        fprintf(node.file,
            "%i" SEPARATION_TOKEN "%llu" SEPARATION_TOKEN "%llu" SEPARATION_TOKEN "%llu" SEPARATION_TOKEN "%u"
            "\n",
            packet_status->idx, packet_status->master_timer_ticks, packet_status->client_timer_ticks,
            packet_status->estimation_master_ticks,
            packet_status->valid);
    }
    k_mutex_unlock(&node.mutex);
}
References bluesync_msg_client_statistic::client_timer_ticks, bluesync_msg_client_statistic::estimation_master_ticks, bluesync_msg_client_statistic::idx, bluesync_msg_client_statistic::master_timer_ticks, node, SEPARATION_TOKEN, and bluesync_msg_client_statistic::valid.
Referenced by statistic_bluesync_status().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (bluesync_statistic_bsim , CONFIG_BLUESYNC_LOG_LEVEL)
NATIVE_TASK() [1/2]
NATIVE_TASK (bluesync_statistic_deinit , ON_EXIT , 501)
References bluesync_statistic_deinit().
NATIVE_TASK() [2/2]
NATIVE_TASK (bluesync_statistic_init , BOOT , 101)
References bluesync_statistic_init().
open_stat()
static FILE * open_stat (char * filename, uint32_t device_number) static
Definition at line 96 of file bluesync_statistic_bsim.c.
{
    FILE *fp;
    static char path[250];
    memset(path, 0, sizeof(path));
    snprintf(path, sizeof(path) - 1,
         "%s%s_%i.csv", CONFIG_BLUESYNC_TEST_BABBLESIM_PATH, filename,
         device_number);
    fp = fopen(path, "w");
    __ASSERT(fp != NULL, "Cannot open file");
    return fp;
}
Referenced by bluesync_statistic_init().
statistic_bluesync_status()
void statistic_bluesync_status (bluesync_timestamps_t * elem_master, bluesync_timestamps_t * elem_slave, size_t size)
Analyze and log synchronization statistics based on a series of timestamps.
This function stores master and slave timestamp pairs into a CSV file.
Parameters
elem_master Pointer to the array of master timestamps.
elem_slave Pointer to the array of local timestamps captured by the slave.
size Number of timestamp pairs to process.
Definition at line 75 of file bluesync_statistic_bsim.c.
{
    uint8_t result_bitfield[NB_BYTES_BITFIELD] = {0};
    // Compute bitfield indicating timestamps available in both set
    bitwise_and_bitfields(result_bitfield, elem_master, elem_slave, NB_BYTES_BITFIELD);
    for (size_t i = 0; i < size; i++) {
        struct bluesync_msg_client_statistic stat = {
            .idx = i,
            .master_timer_ticks = elem_master->timer_ticks[i],
            .client_timer_ticks = elem_slave->timer_ticks[i],
            .estimation_master_ticks = elem_slave->remote_est_ticks[i],
            .valid = is_bit_set(result_bitfield, i),
        };
        bluesync_statistic_packet_status(&stat);
    }
}
References bitwise_and_bitfields(), bluesync_statistic_packet_status(), is_bit_set(), NB_BYTES_BITFIELD, and bluesync_timestamps_t::timer_ticks.
Referenced by end_sync_timeslot_process().
Variable Documentation
node
struct node_stat node static
Definition at line 51 of file bluesync_statistic_bsim.c.
Referenced by bluesync_statistic_deinit(), bluesync_statistic_init(), bluesync_statistic_packet_status(), synced_time_logger_deinit(), synced_time_logger_init(), and synced_time_logger_new_msg().