Bluesync in BLE Mesh: src/bluesync_bitfields.c File Reference
bluesync_bitfields.c File Reference
#include <zephyr/kernel.h>
#include "stdio.h"
#include "bluesync_bitfields.h"
Functions
void print_bitfield_as_binary (uint8_t *bitfield, size_t size)
void set_bit (uint8_t *bitfield, size_t bit_index)
Set a specific bit in the bitfield.
bool is_bit_set (uint8_t *bitfield, size_t bit_index)
Check if a specific bit is set in the bitfield.
void bitwise_and_bitfields (uint8_t *result, const bluesync_timestamps_t *rcv, const bluesync_timestamps_t *local, size_t num_bytes)
Perform a bitwise AND between two bitfields and store the result.
static uint8_t count_bits_in_byte (uint8_t byte)
size_t count_set_bits (uint8_t *bitfield, size_t num_bytes)
Count the number of bits set to 1 in a bitfield.
Function Documentation
bitwise_and_bitfields()
void bitwise_and_bitfields (uint8_t * result, const bluesync_timestamps_t * rcv, const bluesync_timestamps_t * local, size_t num_bytes)
Perform a bitwise AND between two bitfields and store the result.
This is typically used to find common timestamps (slots) between received and local sets.
Parameters
result Output buffer where the result will be stored.
rcv Pointer to the bitfield from received timestamps.
local Pointer to the bitfield from local timestamps.
num_bytes Number of bytes in each bitfield.
Definition at line 45 of file bluesync_bitfields.c.
{
    for (size_t i = 0; i < num_bytes; i++) {
        result[i] = rcv->bitfield[i] & local->bitfield[i];
    }
}
References bluesync_timestamps_t::bitfield, and local.
Referenced by calculate_lr_from_history(), and statistic_bluesync_status().
count_bits_in_byte()
static uint8_t count_bits_in_byte (uint8_t byte) inline static
Definition at line 52 of file bluesync_bitfields.c.
{
    // Using GCC built-in function if available (more efficient)
    #if defined(__GNUC__)
    return __builtin_popcount(byte);
    #else
    // Fallback method: Count bits manually
    uint8_t count = 0;
    while (byte) {
        count += byte & 1;
        byte >>= 1;
    }
    return count;
    #endif
}
Referenced by count_set_bits().
count_set_bits()
size_t count_set_bits (uint8_t * bitfield, size_t num_bytes)
Count the number of bits set to 1 in a bitfield.
Useful for determining how many timeslots have been received.
Parameters
bitfield Pointer to the bitfield array.
num_bytes Number of bytes in the bitfield.
Returns
Number of bits set to 1.
Definition at line 68 of file bluesync_bitfields.c.
{
    size_t total_count = 0;
    for (size_t i = 0; i < num_bytes; i++) {
        total_count += count_bits_in_byte(bitfield[i]);
    }
    return total_count;
}
References count_bits_in_byte().
is_bit_set()
bool is_bit_set (uint8_t * bitfield, size_t bit_index)
Check if a specific bit is set in the bitfield.
Parameters
bitfield Pointer to the bitfield array.
bit_index Index of the bit to check.
Returns
true if the bit is set, false otherwise.
Definition at line 41 of file bluesync_bitfields.c.
{
    return bitfield[bit_index / 8] & BIT(bit_index % 8);
}
Referenced by calculate_lr_from_history(), and statistic_bluesync_status().
print_bitfield_as_binary()
void print_bitfield_as_binary (uint8_t * bitfield, size_t size)
Definition at line 29 of file bluesync_bitfields.c.
{
    printk("0x");
    for (size_t i = size; i-- > 0;) {
        printk("%02X", bitfield[i]);
    }
    printk("\n");
}
set_bit()
void set_bit (uint8_t * bitfield, size_t bit_index)
Set a specific bit in the bitfield.
Parameters
bitfield Pointer to the bitfield array.
bit_index Index of the bit to set.
Definition at line 37 of file bluesync_bitfields.c.
{
    bitfield[bit_index / 8] |= BIT(bit_index % 8);
}
Referenced by add_bluesync_timestamps().