Bluesync in BLE Mesh: src/bs_state_machine.c File Reference
bs_state_machine.c File Reference
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <bluesync/bluesync.h>
#include "bluesync.h"
#include "bs_state_machine.h"
Classes
struct bs_sm_param
Functions
LOG_MODULE_REGISTER (bs_state_machine, CONFIG_BLUESYNC_LOG_LEVEL)
bs_sm_state_t transition (bluesync_role_t role, bs_sm_state_t current_state, bs_sm_event_t event)
void bs_state_machine_run (bs_sm_event_t event)
Annonce an event to the state machine.
void bs_state_machine_init (struct bs_sm_handlers *handlers)
Init the state machine by passing the list of callbacks.
void bs_state_machine_set_role (bluesync_role_t role)
Indicate the role to the state machine.
bluesync_role_t bs_state_machine_get_role ()
Get the node role.
bs_sm_state_t bs_state_machine_get_state ()
Get the current state.
Variables
static struct bs_sm_param sm_param
Function Documentation
bs_state_machine_get_role()
bluesync_role_t bs_state_machine_get_role ()
Get the node role.
Returns
bluesync_role_t
Definition at line 184 of file bs_state_machine.c.
{
    return sm_param.role;
}
References sm_param.
Referenced by bluesync_start_net_sync(), and bluesync_start_net_sync_with_unix_epoch_us().
bs_state_machine_get_state()
bs_sm_state_t bs_state_machine_get_state ()
Get the current state.
Returns
bs_sm_state_t
Definition at line 188 of file bs_state_machine.c.
{
    return sm_param.current_state;
}
References sm_param.
Referenced by bluesync_scan_packet_process().
bs_state_machine_init()
void bs_state_machine_init (struct bs_sm_handlers * handlers)
Init the state machine by passing the list of callbacks.
Parameters
handlers
Definition at line 152 of file bs_state_machine.c.
{
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.handlers = handlers;
    }
    k_mutex_unlock(&sm_param.mutex);
}
References handlers, and sm_param.
Referenced by bluesync_thread_fnt().
bs_state_machine_run()
void bs_state_machine_run (bs_sm_event_t event)
Annonce an event to the state machine.
Parameters
event
Definition at line 107 of file bs_state_machine.c.
{
    if (sm_param.handlers == NULL){
        LOG_ERR("Error: no handlers set...");
        return;
    }
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.current_state = transition(sm_param.role, sm_param.current_state, event);
    }
    k_mutex_unlock(&sm_param.mutex);
    // Call the appropriate handler for the current state
    switch (sm_param.current_state) {
        case BS_SCAN_WAIT_FOR_SYNC:
            if (sm_param.handlers->bs_scan_wait_for_sync_cb){
                sm_param.handlers->bs_scan_wait_for_sync_cb();
            }
            break;
        case BS_SYNC:
            if (sm_param.handlers->bs_sync_cb){
                sm_param.handlers->bs_sync_cb();
            }
            break;
        case BS_UPDATE:
            if (sm_param.handlers->bs_update_cb){
                sm_param.handlers->bs_update_cb();
            }
            break;
        case BS_ADV:
            if (sm_param.handlers->bs_adv_cb){
                sm_param.handlers->bs_adv_cb();
            }
            break;
        case BS_STOP:
            if (sm_param.handlers->bs_stop_cb){
                sm_param.handlers->bs_stop_cb();
            }
            break;
        default:
            break;
    }
}
References BS_ADV, BS_SCAN_WAIT_FOR_SYNC, BS_STOP, BS_SYNC, BS_UPDATE, sm_param, and transition().
Referenced by bluesync_scan_packet_process(), bluesync_thread_fnt(), bs_adv_handler(), and bs_update_handler().
bs_state_machine_set_role()
void bs_state_machine_set_role (bluesync_role_t role)
Indicate the role to the state machine.
Parameters
role
Definition at line 160 of file bs_state_machine.c.
{
    LOG_DBG("set role %d",role );
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.role = role;
        switch (sm_param.role)
        {
        case BLUESYNC_AUTHORITY_ROLE:
            sm_param.current_state = BS_STOP;
            break;
        case BLUESYNC_CLIENT_ROLE:
            sm_param.current_state = BS_SCAN_WAIT_FOR_SYNC;
            break;
        default:
            sm_param.current_state = BS_NONE_STATE;
            break;
        }
    }
    k_mutex_unlock(&sm_param.mutex);
}
References BLUESYNC_AUTHORITY_ROLE, BLUESYNC_CLIENT_ROLE, BS_NONE_STATE, BS_SCAN_WAIT_FOR_SYNC, BS_STOP, bs_sm_param::role, and sm_param.
Referenced by bluesync_set_role().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (bs_state_machine , CONFIG_BLUESYNC_LOG_LEVEL)
transition()
bs_sm_state_t transition (bluesync_role_t role, bs_sm_state_t current_state, bs_sm_event_t event)
Definition at line 48 of file bs_state_machine.c.
{
    switch (current_state) {
        case BS_SCAN_WAIT_FOR_SYNC:
            if (event == EVENT_NEW_SYNC_RCV){
                LOG_DBG("Transition: BS_SCAN_WAIT_FOR_SYNC -> BS_SYNC");
                return BS_SYNC;
            }
            break;
        case BS_SYNC:
            if (event == EVENT_SYNC_EXPIRED){
                LOG_DBG("Transition: BS_SYNC -> BS_UPDATE");
                return BS_UPDATE;
            }
            break;
        case BS_UPDATE:
            if (event == EVENT_UPDATE_SUCCESS){
                LOG_DBG("Transition: BS_UPDATE -> BS_ADV");
                return BS_ADV;
            }
            else if (event == EVENT_UPDATE_FAILED){
                LOG_DBG("Transition: BS_UPDATE -> BS_SCAN_WAIT_FOR_SYNC");
                return BS_SCAN_WAIT_FOR_SYNC;
            }
            break;
        case BS_ADV:
            if (event == EVENT_ADV_EXPIRED){
                if (role == BLUESYNC_AUTHORITY_ROLE){
                    LOG_DBG("Transition: BS_ADV -> BS_STOP");
                    return BS_STOP;
                }
                else if (role == BLUESYNC_CLIENT_ROLE){
                    LOG_DBG("Transition: BS_ADV -> BS_WAIT_SYNC");
                    return BS_SCAN_WAIT_FOR_SYNC;
                }
            }
            break;
        case BS_STOP:
            if (event == EVENT_NEW_NET_SYNC){
                LOG_DBG("Transition: BS_STOP -> BS_ADV");
                return BS_ADV;
            }
            break;
        default:
            if (event == EVENT_INIT){
                if (role == BLUESYNC_AUTHORITY_ROLE){
                    LOG_DBG("Transition: INIT -> BS_STOP");
                    return BS_STOP;
                }
                else if (role == BLUESYNC_CLIENT_ROLE){
                    LOG_DBG("Transition: INIT -> BS_WAIT_SYNC");
                    return BS_SCAN_WAIT_FOR_SYNC;
                }
            }
            break;
    }
    return current_state; // No state change
}
References BLUESYNC_AUTHORITY_ROLE, BLUESYNC_CLIENT_ROLE, BS_ADV, BS_SCAN_WAIT_FOR_SYNC, BS_STOP, BS_SYNC, BS_UPDATE, bs_sm_param::current_state, EVENT_ADV_EXPIRED, EVENT_INIT, EVENT_NEW_NET_SYNC, EVENT_NEW_SYNC_RCV, EVENT_SYNC_EXPIRED, EVENT_UPDATE_FAILED, EVENT_UPDATE_SUCCESS, and bs_sm_param::role.
Referenced by bs_state_machine_run().
Variable Documentation
sm_param
struct bs_sm_param sm_param static
Initial value:
= {
    .role = BLUESYNC_NONE_ROLE,
    .current_state = BS_NONE_STATE,
    .handlers = NULL,
    .mutex = Z_MUTEX_INITIALIZER(sm_param.mutex)
}
Definition at line 41 of file bs_state_machine.c.
{
    .role = BLUESYNC_NONE_ROLE,
    .current_state = BS_NONE_STATE,
    .handlers = NULL,
    .mutex = Z_MUTEX_INITIALIZER(sm_param.mutex)
};
Referenced by bs_state_machine_get_role(), bs_state_machine_get_state(), bs_state_machine_init(), bs_state_machine_run(), and bs_state_machine_set_role().