Bluesync in BLE Mesh: src/bs_state_machine.h File Reference
bs_state_machine.h File Reference
#include "bluesync.h"
Classes
struct bs_sm_handlers
Struct defining the callbacks of the state machine.
Enumerations
enum bs_sm_state_t {
BS_NONE_STATE = 0 , BS_SCAN_WAIT_FOR_SYNC = 1 , BS_SYNC = 2 , BS_UPDATE = 3 ,
BS_ADV = 4 , BS_STOP = 5 , BS_COUNT = 6
}
Type definition representing the states.
enum bs_sm_event_t {
EVENT_NONE = 0 , EVENT_INIT = 1 , EVENT_NEW_SYNC_RCV = 2 , EVENT_SYNC_EXPIRED = 3 ,
EVENT_UPDATE_SUCCESS = 4 , EVENT_UPDATE_FAILED = 5 , EVENT_ADV_EXPIRED = 6 , EVENT_NEW_NET_SYNC = 7 ,
EVENT_COUNT = 8
}
Type definition representing the events.
Functions
void bs_state_machine_run (bs_sm_event_t event)
Annonce an event to the state machine.
void bs_state_machine_init (struct bs_sm_handlers *handlers)
Init the state machine by passing the list of callbacks.
void bs_state_machine_set_role (bluesync_role_t role)
Indicate the role to the state machine.
bluesync_role_t bs_state_machine_get_role ()
Get the node role.
bs_sm_state_t bs_state_machine_get_state ()
Get the current state.
Variables
struct bs_sm_handlers * bs_sm_handlers
This struct is implemented in the bluesync.c file.
Enumeration Type Documentation
bs_sm_event_t
enum bs_sm_event_t
Type definition representing the events.
Enumerator
EVENT_NONE
EVENT_INIT
EVENT_NEW_SYNC_RCV
EVENT_SYNC_EXPIRED
EVENT_UPDATE_SUCCESS
EVENT_UPDATE_FAILED
EVENT_ADV_EXPIRED
EVENT_NEW_NET_SYNC
EVENT_COUNT
Definition at line 47 of file bs_state_machine.h.
             {
    EVENT_NONE                = 0,
    EVENT_INIT                = 1,
    EVENT_NEW_SYNC_RCV        = 2,
    EVENT_SYNC_EXPIRED        = 3,
    EVENT_UPDATE_SUCCESS    = 4,
    EVENT_UPDATE_FAILED  = 5,
    EVENT_ADV_EXPIRED      = 6,
    EVENT_NEW_NET_SYNC        = 7,
    EVENT_COUNT          = 8
} bs_sm_event_t;
bs_sm_state_t
enum bs_sm_state_t
Type definition representing the states.
Enumerator
BS_NONE_STATE
BS_SCAN_WAIT_FOR_SYNC
BS_SYNC
BS_UPDATE
BS_ADV
BS_STOP
BS_COUNT
Definition at line 33 of file bs_state_machine.h.
             {
    BS_NONE_STATE          = 0,
    BS_SCAN_WAIT_FOR_SYNC  = 1,
    BS_SYNC              = 2,
    BS_UPDATE              = 3,
    BS_ADV                    = 4,
    BS_STOP              = 5,
    BS_COUNT                = 6
} bs_sm_state_t;
Function Documentation
bs_state_machine_get_role()
bluesync_role_t bs_state_machine_get_role ()
Get the node role.
Returns
bluesync_role_t
Definition at line 184 of file bs_state_machine.c.
{
    return sm_param.role;
}
References sm_param.
Referenced by bluesync_start_net_sync(), and bluesync_start_net_sync_with_unix_epoch_us().
bs_state_machine_get_state()
bs_sm_state_t bs_state_machine_get_state ()
Get the current state.
Returns
bs_sm_state_t
Definition at line 188 of file bs_state_machine.c.
{
    return sm_param.current_state;
}
References sm_param.
Referenced by bluesync_scan_packet_process().
bs_state_machine_init()
void bs_state_machine_init (struct bs_sm_handlers * handlers)
Init the state machine by passing the list of callbacks.
Parameters
handlers
Definition at line 152 of file bs_state_machine.c.
{
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.handlers = handlers;
    }
    k_mutex_unlock(&sm_param.mutex);
}
References handlers, and sm_param.
Referenced by bluesync_thread_fnt().
bs_state_machine_run()
void bs_state_machine_run (bs_sm_event_t event)
Annonce an event to the state machine.
Parameters
event
Definition at line 107 of file bs_state_machine.c.
{
    if (sm_param.handlers == NULL){
        LOG_ERR("Error: no handlers set...");
        return;
    }
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.current_state = transition(sm_param.role, sm_param.current_state, event);
    }
    k_mutex_unlock(&sm_param.mutex);
    // Call the appropriate handler for the current state
    switch (sm_param.current_state) {
        case BS_SCAN_WAIT_FOR_SYNC:
            if (sm_param.handlers->bs_scan_wait_for_sync_cb){
                sm_param.handlers->bs_scan_wait_for_sync_cb();
            }
            break;
        case BS_SYNC:
            if (sm_param.handlers->bs_sync_cb){
                sm_param.handlers->bs_sync_cb();
            }
            break;
        case BS_UPDATE:
            if (sm_param.handlers->bs_update_cb){
                sm_param.handlers->bs_update_cb();
            }
            break;
        case BS_ADV:
            if (sm_param.handlers->bs_adv_cb){
                sm_param.handlers->bs_adv_cb();
            }
            break;
        case BS_STOP:
            if (sm_param.handlers->bs_stop_cb){
                sm_param.handlers->bs_stop_cb();
            }
            break;
        default:
            break;
    }
}
References BS_ADV, BS_SCAN_WAIT_FOR_SYNC, BS_STOP, BS_SYNC, BS_UPDATE, sm_param, and transition().
Referenced by bluesync_scan_packet_process(), bluesync_thread_fnt(), bs_adv_handler(), and bs_update_handler().
bs_state_machine_set_role()
void bs_state_machine_set_role (bluesync_role_t role)
Indicate the role to the state machine.
Parameters
role
Definition at line 160 of file bs_state_machine.c.
{
    LOG_DBG("set role %d",role );
    k_mutex_lock(&sm_param.mutex, K_FOREVER);
    {
        sm_param.role = role;
        switch (sm_param.role)
        {
        case BLUESYNC_AUTHORITY_ROLE:
            sm_param.current_state = BS_STOP;
            break;
        case BLUESYNC_CLIENT_ROLE:
            sm_param.current_state = BS_SCAN_WAIT_FOR_SYNC;
            break;
        default:
            sm_param.current_state = BS_NONE_STATE;
            break;
        }
    }
    k_mutex_unlock(&sm_param.mutex);
}
References BLUESYNC_AUTHORITY_ROLE, BLUESYNC_CLIENT_ROLE, BS_NONE_STATE, BS_SCAN_WAIT_FOR_SYNC, BS_STOP, bs_sm_param::role, and sm_param.
Referenced by bluesync_set_role().
Variable Documentation
bs_sm_handlers
struct bs_sm_handlers* bs_sm_handlers extern
This struct is implemented in the bluesync.c file.