Bluesync in BLE Mesh: include/bluesync/bluesync.h File Reference
bluesync.h File Reference
#include <zephyr/kernel.h>
Enumerations
enum bluesync_role_t { BLUESYNC_NONE_ROLE = 0 , BLUESYNC_AUTHORITY_ROLE = 1 , BLUESYNC_CLIENT_ROLE = 2 }
Functions
void bluesync_init ()
Initializes the BlueSync time synchronization module.
void bluesync_set_role (bluesync_role_t role)
Sets the operational role of the BlueSync node.
void bluesync_start_net_sync ()
Initiates a new BlueSync synchronization round as the time authority.
void bluesync_start_net_sync_with_unix_epoch_us (uint64_t unix_epoch_us)
Initiates a new BlueSync synchronization round as the time authority.
uint64_t get_current_unix_time_us (void)
Get the current time which is based on the UNIX reference.
Enumeration Type Documentation
bluesync_role_t
enum bluesync_role_t
Enumerator
BLUESYNC_NONE_ROLE
BLUESYNC_AUTHORITY_ROLE
BLUESYNC_CLIENT_ROLE
Definition at line 29 of file bluesync.h.
             {
    BLUESYNC_NONE_ROLE = 0,
    BLUESYNC_AUTHORITY_ROLE = 1,
    BLUESYNC_CLIENT_ROLE = 2
} bluesync_role_t;
Function Documentation
bluesync_init()
void bluesync_init ()
Initializes the BlueSync time synchronization module.
This function sets up internal data structures, mutexes, and state variables required for BlueSync to operate. It should be called once at startup before any synchronization or logical time queries are made.
Definition at line 634 of file bluesync.c.
                    {
    LOG_DBG("bluesync init");
    k_tid_t thread_id = k_thread_create(&param.bluesync_thread, bluesync_thread_stack,
                                      K_THREAD_STACK_SIZEOF(bluesync_thread_stack),
                                      bluesync_thread_fnt, &param, NULL, NULL,
                                      CONFIG_BLUESYNC_THREAD_PRIORITY, 0, K_NO_WAIT);
    k_thread_name_set(thread_id, "bluesync_thread");
}
References bluesync_thread_fnt(), and param.
bluesync_set_role()
void bluesync_set_role (bluesync_role_t role)
Sets the operational role of the BlueSync node.
This function configures the role of the device within the BlueSync synchronization system. Roles define whether the device acts as a time authority or as a time client within the network.
A time authority is the unique source of reference time and distributes it throughout the network. A time client receives synchronization from the authority or other clients and can forward the synchronized time further once it is synchronized.
Parameters
role The role to assign to the device. Must be one of the values defined in the bluesync_role_t enumeration:
BLUESYNC_AUTHORITY_ROLE
BLUESYNC_CLIENT_ROLE
Definition at line 644 of file bluesync.c.
{
    if (role != BLUESYNC_NONE_ROLE) {
        bs_state_machine_set_role(role);
        k_sem_give(&bluesync_role_assign_sem);
    }
    else {
        LOG_ERR("Wrong type given");
    }
}
References BLUESYNC_NONE_ROLE, and bs_state_machine_set_role().
bluesync_start_net_sync()
void bluesync_start_net_sync ()
Initiates a new BlueSync synchronization round as the time authority.
This function is called by the node acting as the time authority to start a network-wide synchronization round. It broadcasts timing information to all clients, allowing them to synchronize their local clocks based on the authority's reference time.
This function should only be called by devices assigned the BLUESYNC_AUTHORITY_ROLE.
Definition at line 655 of file bluesync.c.
{
    if(bs_state_machine_get_role() == BLUESYNC_AUTHORITY_ROLE){
        k_mutex_lock(&param.mutex, K_FOREVER);
        {
            param.current_round_id++;
        }
        k_mutex_unlock(&param.mutex);
        k_sem_give(&bluesync_start_new_sync_sem);
    }
}
References BLUESYNC_AUTHORITY_ROLE, bs_state_machine_get_role(), and param.
Referenced by bluesync_start_net_sync_with_unix_epoch_us().
bluesync_start_net_sync_with_unix_epoch_us()
void bluesync_start_net_sync_with_unix_epoch_us (uint64_t unix_epoch_us)
Initiates a new BlueSync synchronization round as the time authority.
This function is called by the node acting as the time authority to start a network-wide synchronization round. It broadcasts timing information to all clients, allowing them to synchronize their local clocks based on the authority's reference time.
This function should only be called by devices assigned the BLUESYNC_AUTHORITY_ROLE.
Parameters
unix_epoch_ms : unix epoch reference in us
Definition at line 666 of file bluesync.c.
{
    if(bs_state_machine_get_role() == BLUESYNC_AUTHORITY_ROLE){
        //set the new reference unix_epoch
        set_new_epoch_unix_ref(unix_epoch_us);
        //start a new sync in the network
        bluesync_start_net_sync();
    }
}
References BLUESYNC_AUTHORITY_ROLE, bluesync_start_net_sync(), bs_state_machine_get_role(), and set_new_epoch_unix_ref().
get_current_unix_time_us()
uint64_t get_current_unix_time_us (void)
Get the current time which is based on the UNIX reference.
Returns
return unix timestamp in microsecond in uint64_t
Definition at line 138 of file local_time.c.
{
    return ticks_to_us_unix_time(get_logical_time_ticks());
}
References get_logical_time_ticks(), and ticks_to_us_unix_time().
Referenced by my_work_handler().