site_name: BlueSync Documentation
theme: material
nav:
  - Home: index.md
  - Conception: conception.md
  - Implementation: implementation.md
  - API Reference: api/group__bluesync__api.html
  - Kconfig Options: kconfig.md