Bluesync in BLE Mesh: src/statistic/synced_time_logger.h File Reference
synced_time_logger.h File Reference
#include <stdint.h>
Functions
void synced_time_logger_init ()
Initialize the timer that store regularly timestamp of the node.
void synced_time_logger_deinit ()
Deinitialize the timer that store regularly timestamp of the node.
Function Documentation
synced_time_logger_deinit()
void synced_time_logger_deinit ()
Deinitialize the timer that store regularly timestamp of the node.
Definition at line 135 of file synced_time_logger.c.
{
    fclose(node.file);
}
References node.
Referenced by bluesync_statistic_deinit().
synced_time_logger_init()
void synced_time_logger_init ()
Initialize the timer that store regularly timestamp of the node.
Definition at line 111 of file synced_time_logger.c.
{
    uint32_t device_number = bsim_args_get_global_device_nbr();
    node.file = open_stat("node", device_number);
    fprintf(node.file, "val" SEPARATION_TOKEN "timestamp"
               "\n");
    init_sync_overall_timer();
}
References init_sync_overall_timer(), node, open_stat(), and SEPARATION_TOKEN.
Referenced by bluesync_statistic_init().