Bluesync in BLE Mesh: src/statistic/synced_time_logger.c File Reference
synced_time_logger.c File Reference
#include "synced_time_logger.h"
#include <zephyr/kernel.h>
#include "posix_native_task.h"
#include "bsim_args_runner.h"
#include <stdio.h>
#include <string.h>
#include <zephyr/logging/log.h>
#include <bluesync/bluesync.h>
Classes
struct msg_statistic
struct ble_node_stat
Macros
#define SEPARATION_TOKEN ";"
#define TICKS_PER_SECOND 32768
Functions
LOG_MODULE_REGISTER (synced_time_logger, CONFIG_APP_LOG_LEVEL)
void synced_time_logger_new_msg (struct msg_statistic *msg)
void my_work_handler (struct k_work *work)
void timer_handler (struct k_timer *timer_id)
K_TIMER_DEFINE (aligned_timer, timer_handler, NULL)
void init_sync_overall_timer (void)
static FILE * open_stat (char *filename, uint32_t device_number)
void synced_time_logger_init ()
Initialize the timer that store regularly timestamp of the node.
void synced_time_logger_deinit ()
Deinitialize the timer that store regularly timestamp of the node.
Variables
struct k_work my_work
static int64_t val_ref = 0
static struct ble_node_stat node
Macro Definition Documentation
SEPARATION_TOKEN
#define SEPARATION_TOKEN ";"
Definition at line 39 of file synced_time_logger.c.
TICKS_PER_SECOND
#define TICKS_PER_SECOND 32768
Definition at line 41 of file synced_time_logger.c.
Referenced by init_sync_overall_timer().
Function Documentation
init_sync_overall_timer()
void init_sync_overall_timer (void)
Definition at line 69 of file synced_time_logger.c.
{
    k_work_init(&my_work, my_work_handler);
    uint64_t now_ticks = k_uptime_ticks();
    const uint64_t TICKS_PER_20SEC = TICKS_PER_SECOND * 20;
    // Calculate ticks to wait until the next aligned 1-second boundary
    uint64_t remainder = now_ticks % TICKS_PER_20SEC;
    uint64_t ticks_until_next = (remainder == 0) ? 0 : (TICKS_PER_20SEC - remainder);
    LOG_DBG("Now ticks: %llu", now_ticks);
    LOG_DBG("First timer in %llu ticks (aligned to 1s)", ticks_until_next);
    // Start periodic timer: delay to next aligned second, then every second
    k_timer_start(&aligned_timer, K_TICKS(ticks_until_next), K_TICKS(TICKS_PER_SECOND));
}
References my_work, my_work_handler(), and TICKS_PER_SECOND.
Referenced by synced_time_logger_init().
K_TIMER_DEFINE()
K_TIMER_DEFINE (aligned_timer , timer_handler , NULL)
References timer_handler().
LOG_MODULE_REGISTER()
LOG_MODULE_REGISTER (synced_time_logger , CONFIG_APP_LOG_LEVEL)
my_work_handler()
void my_work_handler (struct k_work * work)
Definition at line 52 of file synced_time_logger.c.
{
    struct msg_statistic msg = {
        .timestamp = get_current_unix_time_us(),
        .val = val_ref++,
    };
    synced_time_logger_new_msg(&msg);
}
References get_current_unix_time_us(), synced_time_logger_new_msg(), and val_ref.
Referenced by init_sync_overall_timer().
open_stat()
static FILE * open_stat (char * filename, uint32_t device_number) static
Definition at line 95 of file synced_time_logger.c.
{
    FILE *fp;
    static char path[250];
    memset(path, 0, sizeof(path));
    snprintf(path, sizeof(path) - 1,
         "%s%s_%i.csv",CONFIG_BLUESYNC_TEST_BABBLESIM_PATH,
         filename, device_number);
    LOG_DBG("path : %s\n", path);
    fp = fopen(path, "w");
    __ASSERT(fp != NULL, "Cannot open file");
    return fp;
}
Referenced by synced_time_logger_init().
synced_time_logger_deinit()
void synced_time_logger_deinit ()
Deinitialize the timer that store regularly timestamp of the node.
Definition at line 135 of file synced_time_logger.c.
{
    fclose(node.file);
}
References node.
Referenced by bluesync_statistic_deinit().
synced_time_logger_init()
void synced_time_logger_init ()
Initialize the timer that store regularly timestamp of the node.
Definition at line 111 of file synced_time_logger.c.
{
    uint32_t device_number = bsim_args_get_global_device_nbr();
    node.file = open_stat("node", device_number);
    fprintf(node.file, "val" SEPARATION_TOKEN "timestamp"
               "\n");
    init_sync_overall_timer();
}
References init_sync_overall_timer(), node, open_stat(), and SEPARATION_TOKEN.
Referenced by bluesync_statistic_init().
synced_time_logger_new_msg()
void synced_time_logger_new_msg (struct msg_statistic * msg)
Definition at line 123 of file synced_time_logger.c.
{
    k_mutex_lock(&node.mutex, K_FOREVER);
    {
        fprintf(node.file,
            "%lld" SEPARATION_TOKEN "%llu"
            "\n",
            msg->val, msg->timestamp);
    }
    k_mutex_unlock(&node.mutex);
}
References node, SEPARATION_TOKEN, msg_statistic::timestamp, and msg_statistic::val.
Referenced by my_work_handler().
timer_handler()
void timer_handler (struct k_timer * timer_id)
Definition at line 62 of file synced_time_logger.c.
{
    k_work_submit(&my_work);
}
References my_work.
Referenced by K_TIMER_DEFINE().
Variable Documentation
my_work
struct k_work my_work
Definition at line 42 of file synced_time_logger.c.
Referenced by init_sync_overall_timer(), and timer_handler().
node
struct ble_node_stat node static
Definition at line 93 of file synced_time_logger.c.
val_ref
int64_t val_ref = 0 static
Definition at line 43 of file synced_time_logger.c.
Referenced by my_work_handler().